# Generated by Django 5.2.1 on 2025-06-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_post_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
